/*
 * Isagog Knowledge Graph Service
 * Isagog Knowledge Service API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ks-api@isagog.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.isagog.kg.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.isagog.kg.model.Support;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for QueryResponseItem
 */
public class QueryResponseItemTest {
    private final QueryResponseItem model = new QueryResponseItem();

    /**
     * Model tests for QueryResponseItem
     */
    @Test
    public void testQueryResponseItem() {
        // TODO: test QueryResponseItem
    }

    /**
     * Test the property 'row'
     */
    @Test
    public void rowTest() {
        // TODO: test row
    }

    /**
     * Test the property 'support'
     */
    @Test
    public void supportTest() {
        // TODO: test support
    }

}
