/*
 * Isagog Knowledge Graph Service
 * Isagog Knowledge Service API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ks-api@isagog.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.isagog.kg.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.isagog.kg.model.AttributiveSlot;
import com.isagog.kg.model.ConceptualSlot;
import com.isagog.kg.model.RelationalSlot;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Slot
 */
public class SlotTest {
    private final Slot model = new Slot();

    /**
     * Model tests for Slot
     */
    @Test
    public void testSlot() {
        // TODO: test Slot
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'stype'
     */
    @Test
    public void stypeTest() {
        // TODO: test stype
    }

    /**
     * Test the property 'mandatory'
     */
    @Test
    public void mandatoryTest() {
        // TODO: test mandatory
    }

    /**
     * Test the property 'distinguished'
     */
    @Test
    public void distinguishedTest() {
        // TODO: test distinguished
    }

    /**
     * Test the property 'informative'
     */
    @Test
    public void informativeTest() {
        // TODO: test informative
    }

    /**
     * Test the property 'ontologyReference'
     */
    @Test
    public void ontologyReferenceTest() {
        // TODO: test ontologyReference
    }

}
