openapi: 3.0.2
info:
  title: Isagog Knowledge Graph Data Service
  version: 1.0.0
  description: Isagog Knowledge Graph Data endpoints
  contact:
    email: ks-api@isagog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost
    variables:
      port:
        default: '3200'
      basePath:
        default: /kg
tags:

  - name: DataService
    description: CRUD and queries over the data layer

paths:

  /data/create:
    post:
      summary: Knowledge graph creation
      description: Creates a Knowledge graph
      operationId: createGraph
      responses:
        200:
          description: Success
        401:
          description: Duplicated ID
        402:
          description: Invalid Graph
        501:
          description: Service unavailable
        502:
          description: Server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: kg-knowledge.yaml#/components/schemas/KnowledgeGraph
        description: The graph to be created
        required: true
      tags:
        - DataService

  /data/list:
    get:
      summary: Lists Knowledge Graphs
      description: Returns the list of available KGs (id)
      operationId: listGraphs
      parameters:
        - name: summary
          in: query
          required: false
          schema:
            type: boolean
            default: false
      responses:
        200:
          description: Success, KG id list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: id
        201:
          description: Success, KG summary (id,description,size) list
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: kg-knowledge.yaml#/components/schemas/KnowledgeGraph

      tags:
        - DataService

  /data/delete:
    get:
      summary: Deletes a Knowledge Graph
      description: Knowledge graph deletion
      operationId: deleteGraph
      parameters:
        - name: kg
          in: query
          required: true
          schema:
            type: string
            format: id
          description: The Knowledge Graph identifier

      responses:
        200:
          description: Success
        401:
          description: Unknown Graph
        402:
          description: Dependencies violation
        501:
          description: Service unavailable
        502:
          description: Server error
      tags:
        - DataService

  /data/get:
    get:
      summary: Retrieves an entity
      description: Get the named entity, if present
      parameters:
        - name: kg
          in: query
          required: false
          schema:
            type: string
            format: id
        - name: id
          in: query
          required: true
          schema:
            type: string
            format: id

      operationId: getEntity
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                 $ref: kg-knowledge.yaml#/components/schemas/Entity
        401:
          description: Unknown graph
        402:
          description: Unknown Entity
        501:
          description: Service unavailable
        502:
          description: Server error
      tags:
        - DataService

  /data/assert:
    post:
      summary: Statement assertion
      description: Asserts a statement in a Knowledge Graph
      parameters:
        - name: kg
          in: query
          required: true
          schema:
            type: string
          description: Assertion context (KG id)
      operationId: assertStatement
      responses:
        200:
          description: Success
        401:
          description: Unknown graph
        402:
          description: Malformed statement
        403:
          description: Unsupported statement
        501:
          description: Service unavailable
        502:
          description: Server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: kg-knowledge.yaml#/components/schemas/EntityStatement
        description: Assertion statement
        required: true
      tags:
        - DataService


  /data/retract:
    post:
      summary: Statement retraction
      description: Retracts a statement and all the statements depending on it
      parameters:
        - name: kg
          in: query
          required: true
          schema:
            type: string
      operationId: retractStatement
      responses:
        200:
          description: Success
        401:
          description: Unknown graph
        402:
          description: Malformed statement
        403:
          description: Unsupported statement
        501:
          description: Service unavailable
        502:
          description: Server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: kg-knowledge.yaml#/components/schemas/EntityStatement
        description: Retraction statement
        required: true
      tags:
        - DataService


  /data/search:
    get:
      summary: Knowledge search
      description: Search knowledge items
      operationId: search
      parameters:
        - name: kg
          in: query
          required: false
          schema:
            type: string
            format: id
          description: Search context (opt)
        - name: query
          in: query
          description: The query to search by
          required: true
          explode: false
          schema:
            type: string
        - name: attribute
          in: query
          description: The attribute to search by (opt)
          required: false
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: kg-knowledge.yaml#/components/schemas/Entity
        201:
          description: No results
        401:
          description: Unknown graph
        402:
          description: Invalid key
        501:
          description: Service unavailable
        502:
          description: Server error
      tags:
        - DataService

  /data/query:
    post:
      summary: Knowledge query
      description: Queries a Knowledge Graph
      parameters:
        - name: kg
          in: query
          required: false
          schema:
            type: string
            format: id
          description: Query context (opt)
      operationId: query
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        401:
          description: Unknown graph
        402:
          description: Invalid query
        501:
          description: Service unavailable
        502:
          description: Server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
        description: The query Frame
        required: true
      tags:
        - DataService


components:
  schemas:

    Query:
      description: Query frame
      allOf:
        - $ref: kg-knowledge.yaml#/components/schemas/Frame
      type: object
      properties:
        qtype:
          type: string
          enum:
            - IndividuationQuery
            - CardinalityQuery
            - ExtensionQuery


    QueryResponse:
      description: Query result set
      type: object
      required:
        - header
        - rows
        - report
        - query
      properties:
        query:
          type: string
        header:
          type: array
          items:
            $ref: '#/components/schemas/QueryResponseHeader'
        rows:
          type: array
          items:
            $ref: '#/components/schemas/QueryResponseItem'

    QueryResponseHeader:
      description: Query result set header
      type: object
      required:
        - name
        - dtype
      properties:
        name:
          type: string
        dtype:
          type: string
          enum:
            - Uri
            - Boolean
            - Integer
            - Double
            - String

    QueryResponseItem:
      description: Query result set row
      type: object
      required:
        - row
      properties:
        row:
          type: array
          items:
            type: string
        support:
          $ref: kg-knowledge.yaml#/components/schemas/Support
