openapi: 3.0.2
info:
  title: Isagog Knowledge Graph Data Service
  version: 1.0.0
  description: Isagog Knowledge Graph Data module
  contact:
    name: Isagog Srl
    email: ks-api@isagog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://api.isagog.com
    variables:
      port:
        default: '8030'
      basePath:
        default: /data

tags:
  - name: DataService

paths:

  /query:
    post:
      summary: Knowledge query
      description: Queries a Knowledge Graph
      parameters:
        - name: kg
          in: query
          required: false
          schema:
            type: string
            format: id
          description: Query context (opt)
      operationId: query
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        401:
          description: Unsupported language
        402:
          description: Invalid query
        501:
          description: Service unavailable
        502:
          description: Server error
        503:
          description: Missing implementation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'

        description: The query
        required: true
      tags:
        - DataService

  /upload:
    post:
      summary: Bulk upload
      description: Uploads a resource
      parameters:
        - name: kg
          in: query
          required: true
          schema:
            type: string
      operationId: upload
      responses:
        200:
          description: Success
        401:
          description: Unknown graph
        402:
          description: Malformed document
        403:
          description: Unsupported format
        501:
          description: Service unavailable
        502:
          description: Server error
        503:
          description: Missing implementation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Upload'

      tags:
        - DataService

components:
  schemas:
    Query:
      description: Data query
      type: object
      required:
        - qtype
      properties:
        qtype:
          type: string
      discriminator:
        propertyName: qtype
        mapping:
          QueryFrame: '#/components/schemas/QueryFrame'
          QueryExpression: '#/components/schemas/QueryExpression'
          QueryKeywords: '#/components/schemas/QueryKeywords'

    QueryExpression:
      description: Query structured string
      allOf:
        - $ref: '#/components/schemas/Query'
      type: object
      required:
        - lang
        - body
      properties:
        lang:
          type: string
          enum:
            - SPARQL
            - GRAPHQL
          description: Query language
        query:
          type: string
          format: utf8
          description: Query string

    QueryFrame:
      description: Query frame
      allOf:
        - $ref: '#/components/schemas/Query'
      type: object
      required:
        - qkind
        - frame
      properties:
        qkind:
          type: string
          description: Query kind, where (INDIVIDUATION = single entity, CARDINALITY = entity count, LIST = list of entity n-tuples)
          enum:
            - INDIVIDUATION
            - CARDINALITY
            - LIST
        frame:
          $ref: kg-knowledge.yaml#/components/schemas/FrameInstance

    QueryKeywords:
      description: Keyword-based search
      allOf:
        - $ref: '#/components/schemas/Query'
      type: object
      required:
        - keys
      properties:
        keys:
          type: array
          items:
            type: string
            format: UFT-8
        op:
          type: string
          enum:
            - OR
            - AND
            - EXCEPT
          default: OR
          description: The search operator; OR = at least one match, AND = complete match, EXCEPT = match the first value but not the others



    QueryResponse:
      description: Query result set
      type: object
      required:
        - handle
        - size
        - header
      properties:
        handle:
          type: integer
          format: int64
          description: Handle to the query result, may be used to fetch results
        size:
          type: integer
          format: int32
          description: Total availabe results
        header:
          type: array
          items:
            $ref: '#/components/schemas/QueryResponseHeader'
          description: Result set description
        items:
          type: array
          items:
            $ref: '#/components/schemas/QueryResponseItem'
          description: Result items

    QueryResponseHeader:
      description: Query result set header
      type: object
      required:
        - name
        - dtype
      properties:
        name:
          type: string
        dtype:
          type: string
          enum:
            - Uri
            - Boolean
            - Integer
            - Double
            - String

    QueryResponseItem:
      description: Query result set row
      type: object
      required:
        - row
      properties:
        row:
          type: array
          items:
            type: string
            format: utf8
        support:
          type: number
          format: double
          minimum: 0.0
          maximum: 1.0


    UpdateResponse:
      description: Update response
      type: object
      required:
        - report
      properties:
        report:
          description: Report
          type: array
          items:
            type: object
            properties:
              code:
                type: string
                enum:
                  - OK
                  - WARN
                  - ERROR
              message:
                type: string



    Upload:
      type: object
      properties:
        format:
          type: string
          enum:
            - XML
            - TURTLE
            - N3
            - CSV
            - JSON
        content:
          type: string
          format: byte