openapi: 3.0.2
info:
  title: Isagog Knowledge Graph Ingestion Service
  version: 1.0.0
  description: Isagog Knowledge Graph Ingestion endpoint
  contact:
    email: ks-api@isagog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost
    variables:
      port:
        default: '3205'
      basePath:
        default: /
tags:
  - name: IngestionService
    description: Bulk upload functionalities
paths:

  /ingest/upload:
    post:
      summary: Bulk upload
      description: Uploads an RDF resource
      parameters:
        - name: kg
          in: query
          required: true
          schema:
            type: string
      operationId: uploadResource
      responses:
        200:
          description: Success
        401:
          description: Unknown graph
        402:
          description: Malformed document
        403:
          description: Unsupported format
        501:
          description: Service unavailable
        502:
          description: Server error
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadForm'
      tags:
        - IngestionService


components:
  schemas:


    UploadForm:
      description: Upload form
      type: object
      required:
        - content
      properties:
        format:
          description: Serialization format
          type: string
          enum:
            - turtle
            - rdf-xml
            - rdf-json
            - json-ld
        content:
          description: Serialized content
          type: string
          format: binary



