openapi: 3.0.2
info:
  title: Isagog Knowledge Graph Interaction Service
  version: 1.0.0
  description: Isagog Knowledge Graph Interaction module
  contact:
    name: Isagog Srl
    email: ks-api@isagog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://api.isagog.com
    variables:
      port:
        default: '8030'
      basePath:
        default: /interact
tags:
  - name: InteractionService

paths:

  /input:
    post:
      summary: User input
      description: Processes the user input
      parameters:
        - name: kg
          in: query
          required: false
          schema:
            type: string
          description: Upload context (KG id)
      operationId: input
      responses:
        200:
          description: Acknowledge message
          content:
            text/plain:
              schema:
                type: string
        201:
          description: Query response
          content:
            application/json:
              schema:
                $ref: kg-data.yaml#/components/schemas/QueryResponse
        202:
          description: Frame instantiation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: kg-knowledge.yaml#/components/schemas/Frame
        203:
          description: Sentence analysis
          content:
            application/json:
              schema:
                $ref: kg-language.yaml#/components/schemas/SentenceAnnotation

        401:
          description: Unknown graph
        402:
          description: Illegal input format
        403:
          description: Meaningless input
        501:
          description: Service unavailable
        502:
          description: Server error
        503:
          description: Missing implementation
      requestBody:
        content:
          application/json:
            schema:
              $ref: kg-language.yaml#/components/schemas/Sentence
        description: User input
        required: true
      tags:
        - InteractionService

  /issue:
      post:
        summary: Sends a frame instance for processing
        description: Sends a frame, e.g. a user query form, to the systems
        parameters:
          - name: kg
            in: query
            required: false
            schema:
              type: string
            description: Upload context (KG id)
        operationId: issue
        responses:
          200:
            description: Success acknowledge
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: string
          201:
            description: Query response
            content:
              application/json:
                schema:
                  $ref: kg-data.yaml#/components/schemas/QueryResponse
          202:
            description: Update response
            content:
              application/json:
                schema:
                  $ref: kg-data.yaml#/components/schemas/UpdateResponse
          401:
            description: Unknown graph
          402:
            description: Malformed frame
          501:
            description: Service unavailable
          502:
            description: Server error
          503:
            description: Missing implementation
        requestBody:
          content:
            application/json:
              schema:
                $ref: kg-knowledge.yaml#/components/schemas/Frame
          description: Frame instance
          required: true
        tags:
          - InteractionService

  /complete:
      get:
        summary: Suggets completions
        description: Provides a list of candidate completions to the provided input (hook)
        parameters:
          - name: hook
            in: query
            required: true
            schema:
              type: string
              format: utf8
          - name: context
            in: query
            required: false
            schema:
              type: array
              description: Sorted list of previous completions to provide context (opt)
              items:
                $ref: '#/components/schemas/Completion'
            explode: false
        operationId: complete
        responses:
          200:
            description: List of suitable completion (typed) choices
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/CompletionChoices'
          402:
            description: Illegal hook
          501:
            description: Service unavailable
          502:
            description: Server error
          503:
            description: Missing implementation
        tags:
          - InteractionService



components:
  schemas:

    UploadForm:
      description: Upload form
      type: object
      required:
        - content
      properties:
        format:
          description: Serialization format
          type: string
          enum:
            - turtle
            - rdf-xml
            - rdf-json
            - json-ld
            - txt
            - csv
        content:
          description: Serialized content
          type: string
          format: binary

    CompletionType:
      type: object
      description: Enumeration of completion types
      properties:
        ctype:
           type: string
           enum:
            - ENTITY
            - CONCEPT
            - RELATION
            - ATTRIBUTE
            - QUESTION_WORD
            - CONJUNCTION
            - ANY
           default: ANY

    CompletionChoices:
      description: Typed completion choices
      type: object
      allOf:
        - $ref: '#/components/schemas/CompletionType'
      required:
        - completion
      properties:
        choices:
          description: Completion choices
          type: array
          items:
            type: string
            format: utf8

    Completion:
      description: Actual completion
      type: object
      allOf:
        - $ref: '#/components/schemas/CompletionType'
      required:
        - completion
      properties:
        completion:
          type: string
          format: utf8






