openapi: 3.0.2
info:
  title: Isagog Knowledge Graph Interaction Service
  version: 1.0.0
  description: Isagog Knowledge Graph Interaction module
  contact:
    name: Isagog Srl
    email: ks-api@isagog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost
    variables:
      port:
        default: 3200
      basePath:
        default: /
tags:
  - name: InteractionService

paths:

  /interact/input:
    $ref: kg-openapi.yaml#/interact/input

  /interact/issue:
    $ref: kg-openapi.yaml#/interact/issue


components:
  schemas:

    UploadForm:
      description: Upload form
      type: object
      required:
        - content
      properties:
        format:
          description: Serialization format
          type: string
          enum:
            - turtle
            - rdf-xml
            - rdf-json
            - json-ld
            - txt
            - csv
        content:
          description: Serialized content
          type: string
          format: binary



