openapi: 3.0.2
info:
  title: Isagog Knowledge Graph Interaction Service
  version: 1.0.0
  description: Isagog Knowledge Graph Interaction module
  contact:
    name: Isagog Srl
    email: ks-api@isagog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: localhost:8030
    variables:
      port:
        default: '8030'
      basePath:
        default: /interact
tags:
  - name: InteractionService

paths:


  /issue:
      post:
        summary: Sends an interaction sequence for processing
        description: Sends list of interaction records, to be processed according to the service's buisiness logic
        parameters:
          - name: kg
            in: query
            required: false
            description: Issuing target (opt)
            schema:
              type: string
              format: id
        operationId: issue
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/IssueResponse'
          401:
            description: Unknown graph
          402:
            description: Malformed frame
          501:
            description: Service unavailable
          502:
            description: Server error
          503:
            description: Missing implementation
        requestBody:
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/InteractRecord'
          description: Interaction record array
          required: true
        tags:
          - InteractionService

  /complete:
      get:
        summary: Suggets completions
        description: Provides a list of candidate completions to the provided input (hook)
        parameters:
          - name: hook
            in: query
            description: String to search by
            required: true
            schema:
              type: string
              format: utf-8
          - name: itype
            in: query
            description: Conceptual type restriction (opt)
            required: false
            schema:
              type: string

        operationId: complete
        responses:
          200:
            description: List of suitable completions
            content:
              application/json:
                schema:
                   $ref: '#/components/schemas/CompletionResponse'
          402:
            description: Illegal hook
          501:
            description: Service unavailable
          502:
            description: Server error
          503:
            description: Missing implementation
        tags:
          - InteractionService
      post:
          summary: Suggets completions
          description: Provides completion to the provided hook wrt a frame
          parameters:
            - name: hook
              in: query
              description: String to search by
              required: true
              schema:
                type: string
                format: utf-8
          operationId: completeInContext
          responses:
            200:
              description: List of suitable completions
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/CompletionResponse'
            402:
              description: Illegal hook
            501:
              description: Service unavailable
            502:
              description: Server error
            503:
              description: Missing implementation
          tags:
            - InteractionService
          requestBody:
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/InteractRecord'



components:
  schemas:

    UploadForm:
      description: Upload form
      type: object
      required:
        - content
      properties:
        format:
          description: Serialization format
          type: string
          enum:
            - turtle
            - rdf-xml
            - rdf-json
            - json-ld
            - txt
            - csv
        content:
          description: Serialized content
          type: string
          format: binary

    InteractType:
      description: Interaction conceptual types
      type: string
      enum:
        - VALUE
        - ENTITY
        - CONCEPT
        - RELATION
        - ATTRIBUTE
        - FRAME
        - SYNTAGM

    ResponseType:
      description: Interaction response type
      type: string
      enum:
        - QUERY_ANSWER
        - SEARCH_ANSWER
        - UPDATE_ACKNOWLEDGE
        - ERROR


    InteractRecord:
      description: Interaction record
      type: object
      required:
        - itype
        - value
      properties:
        itype:
          $ref: '#/components/schemas/InteractType'
        kitem:
          description: Knowlege item (opt)
          type: string
          format: id
        constraints:
          description: Knowledge constraints (opt)
          type: array
          items:
            type: string
        slot:
          $ref: kg-knowledge.yaml#/components/schemas/SlotReference
        value:
          description: Interaction content
          type: string
          format: utf-8



    CompletionResponse:
      description: Completion array
      type: object
      properties:
        suggestions:
          description: Suggested interactions, should be sorted by type (itype)
          type: array
          items:
            $ref: '#/components/schemas/InteractRecord'



    IssueResponse:
     description: Response to issuing an interation
     type: object
     required:
       - rtype
     properties:
       rtype:
         $ref: '#/components/schemas/ResponseType'
       qanswer:
         $ref: kg-data.yaml#/components/schemas/QueryResponse
       upanswer:
         $ref: kg-data.yaml#/components/schemas/UpdateResponse
       message:
         type: string





