openapi: 3.0.2
info:
  title: Isagog Knowledge Graph Interaction Service
  version: 1.0.0
  description: Isagog Knowledge Graph Interacrion endpoint
  contact:
    email: ks-api@isagog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost
    variables:
      port:
        default: '3200'
      basePath:
        default: /kg
tags:
  - name: InteractionService

paths:



  /interact/input:
    post:
      summary: User input
      description: Processes the user input
      parameters:
        - name: lang
          in: query
          required: false
          schema:
            type: string
            enum:
              - en
              - it
              - de
              - fr
              - es
            default: en
      operationId: userInput
      responses:
        200:
          description: Query response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QueryResponse'
        201:
          description: Frame instantiation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: kg-knowledge.yaml#/components/schemas/FrameInstance
        202:
          description: Sentence analysis
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: kg-language.yaml#/components/schemas/SentenceAnnotation
        203:
          description: Acknowledge message
          content:
            text/plain:
              schema:
                type: string
        401:
          description: Unknown graph
        402:
          description: Illegal input format
        403:
          description: Meaningless input
        501:
          description: Service unavailable
        502:
          description: Server error
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              format: UTF-8
        description: User input
        required: true
      tags:
        - InteractionService

  /interact/pull:
    post:
      summary: Pulls a frame for processing
      description: Sends a frame, e.g. a user query form, to the systems
      parameters:
        - name: kg
          in: query
          required: false
          schema:
            type: string
          description: Upload context (KG id)
      operationId: pullFrame
      responses:
        200:
          description: Query response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QueryResponse'
        203:
          description: Acknowledge message
          content:
            text/plain:
              schema:
                type: string
        401:
          description: Unknown graph
        402:
          description: Malformed frame
        501:
          description: Service unavailable
        502:
          description: Server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: kg-knowledge.yaml#/components/schemas/FrameInstance
        description: Frame instance
        required: true
      tags:
        - InteractionService

components:
  schemas:
    Query:
      description: Query frame
      allOf:
        - $ref: kg-knowledge.yaml#/components/schemas/FrameInstance
      type: object
      properties:
        qtype:
          type: string
          description: Query type
          enum:
            - IndividuationQuery
            - CardinalityQuery
            - ExtensionQuery


    QueryResponse:
      description: Query result set
      type: object
      required:
        - header
        - rows
        - report
        - query
      properties:
        query:
          type: string
        header:
          type: array
          items:
            $ref: '#/components/schemas/QueryResponseHeader'
        rows:
          type: array
          items:
            $ref: '#/components/schemas/QueryResponseItem'

    QueryResponseHeader:
      description: Query result set header
      type: object
      required:
        - name
        - dtype
      properties:
        name:
          type: string
        dtype:
          type: string
          enum:
            - Uri
            - Boolean
            - Integer
            - Double
            - String

    QueryResponseItem:
      description: Query result set row
      type: object
      required:
        - row
      properties:
        row:
          type: array
          items:
            type: string
        support:
          type: number
          format: double
          minimum: 0.0
          maximum: 1.0

    Update:
      description: Update frame
      allOf:
        - $ref: kg-knowledge.yaml#/components/schemas/FrameInstance
      type: object

    UploadForm:
      description: Upload form
      type: object
      required:
        - content
      properties:
        format:
          description: Serialization format
          type: string
          enum:
            - turtle
            - rdf-xml
            - rdf-json
            - json-ld
            - txt
            - csv
        content:
          description: Serialized content
          type: string
          format: binary



