openapi: 3.0.2
info:
  title: Isagog Knowledge Graph Interaction Service
  version: 1.0.0
  description: Isagog Knowledge Graph Interaction module
  contact:
    name: Isagog Srl
    email: ks-api@isagog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://api.isagog.com
    variables:
      port:
        default: '8030'
      basePath:
        default: /interact
tags:
  - name: InteractionService

paths:

#  /input:
#    post:
#      summary: User input
#      description: Processes the user input
#      parameters:
#        - name: kg
#          in: query
#          required: false
#          schema:
#            type: string
#          description: Upload context (KG id)
#      operationId: input
#      responses:
#        200:
#          description: Acknowledge message
#          content:
#            text/plain:
#              schema:
#                type: string
#        201:
#          description: Query response
#          content:
#            application/json:
#              schema:
#                $ref: kg-data.yaml#/components/schemas/QueryResponse
#        202:
#          description: Frame instantiation
#          content:
#            application/json:
#              schema:
#                type: array
#                items:
#                  $ref: kg-knowledge.yaml#/components/schemas/Frame
#        203:
#          description: Sentence analysis
#          content:
#            application/json:
#              schema:
#                $ref: kg-language.yaml#/components/schemas/SentenceAnnotation
#
#        401:
#          description: Unknown graph
#        402:
#          description: Illegal input format
#        403:
#          description: Meaningless input
#        501:
#          description: Service unavailable
#        502:
#          description: Server error
#        503:
#          description: Missing implementation
#      requestBody:
#        content:
#          application/json:
#            schema:
#              $ref: kg-language.yaml#/components/schemas/Sentence
#        description: User input
#        required: true
#      tags:
#        - InteractionService

  /issue:
      post:
        summary: Sends an interaction sequence for processing
        description: Sends list of interaction records, to be processed according to the service's buisiness logic
        parameters:
          - name: kg
            in: query
            required: false
            description: Issuing target (opt)
            schema:
              type: string
              format: id
        operationId: issue
        responses:
          200:
            description: Acknowledge
            content:
              application/json:
                schema:
                  type: string
          201:
            description: Query response
            content:
              application/json:
                schema:
                  $ref: kg-data.yaml#/components/schemas/QueryResponse
          202:
            description: Update response
            content:
              application/json:
                schema:
                  $ref: kg-data.yaml#/components/schemas/UpdateResponse
          401:
            description: Unknown graph
          402:
            description: Malformed frame
          501:
            description: Service unavailable
          502:
            description: Server error
          503:
            description: Missing implementation
        requestBody:
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/InteractRecord'
          description: Interaction record array
          required: true
        tags:
          - InteractionService

  /complete:
      get:
        summary: Suggets completions
        description: Provides a list of candidate completions to the provided input (hook)
        parameters:
          - name: hook
            in: query
            description: String to search by
            required: true
            schema:
              type: string
              format: utf-8
          - name: itype
            in: query
            description: Conceptual type restriction (opt)
            required: false
            schema:
              type: string

        operationId: completeString
        responses:
          200:
            description: List of suitable completions
            content:
              application/json:
                schema:
                   $ref: '#/components/schemas/CompletionResponse'
          402:
            description: Illegal hook
          501:
            description: Service unavailable
          502:
            description: Server error
          503:
            description: Missing implementation
        tags:
          - InteractionService
      post:
          summary: Suggets completions
          description: Provides completion to the provided hook wrt a frame
          parameters:
            - name: hook
              in: query
              description: String to search by
              required: true
              schema:
                type: string
                format: utf-8
          operationId: completeFrame
          responses:
            200:
              description: List of suitable completions
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/CompletionResponse'
            402:
              description: Illegal hook
            501:
              description: Service unavailable
            502:
              description: Server error
            503:
              description: Missing implementation
          tags:
            - InteractionService
          requestBody:
            content:
              application/json:
                schema:
                  $ref: kg-knowledge.yaml#/components/schemas/Frame



components:
  schemas:

    UploadForm:
      description: Upload form
      type: object
      required:
        - content
      properties:
        format:
          description: Serialization format
          type: string
          enum:
            - turtle
            - rdf-xml
            - rdf-json
            - json-ld
            - txt
            - csv
        content:
          description: Serialized content
          type: string
          format: binary

    InteractType:
      description: Interaction conceptual types
      type: string
      enum:
        - VALUE
        - ENTITY
        - CONCEPT
        - RELATION
        - ATTRIBUTE
        - FRAME
        - SYNTAGM


    InteractRecord:
      description: Interaction record
      type: object
      required:
        - itype
        - value
      properties:
        itype:
          $ref: '#/components/schemas/InteractType'
        kitem:
          description: Knowlege item (opt)
          type: string
          format: id
        value:
          description: Interaction content
          type: string
          format: utf-8
        binding:
          description: Frame slot binding (opt)
          type: integer
          format: int32
          minimum: 0
          maximum: 128

    CompletionResponse:
      description: Completion array
      type: object
      properties:
        suggestions:
          description: Suggested interactions
          type: array
          items:
            $ref: '#/components/schemas/InteractRecord'











