/*
 * Isagog Knowledge Graph Service
 * Isagog Knowledge Graph Service API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ks-api@isagog.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.isagog.kg.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.isagog.kg.model.SlotValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Frame instance
 */
@ApiModel(description = "Frame instance")
@JsonPropertyOrder({
  FrameInstance.JSON_PROPERTY_FTYPE,
  FrameInstance.JSON_PROPERTY_SLOT_VALUES
})
@JsonTypeName("FrameInstance")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-01T15:11:01.505608900+02:00[Europe/Berlin]")
public class FrameInstance {
  public static final String JSON_PROPERTY_FTYPE = "ftype";
  private String ftype;

  public static final String JSON_PROPERTY_SLOT_VALUES = "slotValues";
  private List<SlotValue> slotValues = null;


  public FrameInstance ftype(String ftype) {
    
    this.ftype = ftype;
    return this;
  }

   /**
   * Frame type identifier
   * @return ftype
  **/
  @ApiModelProperty(required = true, value = "Frame type identifier")
  @JsonProperty(JSON_PROPERTY_FTYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFtype() {
    return ftype;
  }


  public void setFtype(String ftype) {
    this.ftype = ftype;
  }


  public FrameInstance slotValues(List<SlotValue> slotValues) {
    
    this.slotValues = slotValues;
    return this;
  }

  public FrameInstance addSlotValuesItem(SlotValue slotValuesItem) {
    if (this.slotValues == null) {
      this.slotValues = new ArrayList<SlotValue>();
    }
    this.slotValues.add(slotValuesItem);
    return this;
  }

   /**
   * Get slotValues
   * @return slotValues
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SLOT_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SlotValue> getSlotValues() {
    return slotValues;
  }


  public void setSlotValues(List<SlotValue> slotValues) {
    this.slotValues = slotValues;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FrameInstance frameInstance = (FrameInstance) o;
    return Objects.equals(this.ftype, frameInstance.ftype) &&
        Objects.equals(this.slotValues, frameInstance.slotValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ftype, slotValues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FrameInstance {\n");
    sb.append("    ftype: ").append(toIndentedString(ftype)).append("\n");
    sb.append("    slotValues: ").append(toIndentedString(slotValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

