/*
 * Isagog Knowledge Graph Service
 * Isagog Knowledge Graph Service API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ks-api@isagog.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.isagog.kg.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.isagog.kg.model.ClassAnnotation;
import com.isagog.kg.model.DependencyAnnotation;
import com.isagog.kg.model.EntityAnnotation;
import com.isagog.kg.model.GrammarAnnotation;
import com.isagog.kg.model.RelationAnnotation;
import com.isagog.kg.model.Support;
import com.isagog.kg.model.SyntaxAnnotation;
import com.isagog.kg.model.TokenAnnotation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Token grammar spec
 */
@ApiModel(description = "Token grammar spec")
@JsonPropertyOrder({
  GrammarAnnotation.JSON_PROPERTY_POS,
  GrammarAnnotation.JSON_PROPERTY_MODIFIER,
  GrammarAnnotation.JSON_PROPERTY_NUMBER,
  GrammarAnnotation.JSON_PROPERTY_PERSON
})
@JsonTypeName("GrammarAnnotation")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-07T16:45:57.251979+02:00[Europe/Berlin]")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "atype", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = ClassAnnotation.class, name = "ClassAnnotation"),
  @JsonSubTypes.Type(value = DependencyAnnotation.class, name = "DependencyAnnotation"),
  @JsonSubTypes.Type(value = EntityAnnotation.class, name = "EntityAnnotation"),
  @JsonSubTypes.Type(value = GrammarAnnotation.class, name = "GrammarAnnotation"),
  @JsonSubTypes.Type(value = RelationAnnotation.class, name = "RelationAnnotation"),
  @JsonSubTypes.Type(value = SyntaxAnnotation.class, name = "SyntaxAnnotation"),
})

public class GrammarAnnotation extends TokenAnnotation {
  /**
   * Part of speech
   */
  public enum PosEnum {
    NOUN("NOUN"),
    
    VERB("VERB"),
    
    ADJECTIVE("ADJECTIVE"),
    
    ADVERB("ADVERB"),
    
    PRONOUN("PRONOUN"),
    
    NUMERAL("NUMERAL");

    private String value;

    PosEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PosEnum fromValue(String value) {
      for (PosEnum b : PosEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_POS = "pos";
  private PosEnum pos;

  /**
   * Part of speech modifier
   */
  public enum ModifierEnum {
    V_MODAL("V-MODAL"),
    
    V_AUXILIAR("V-AUXILIAR"),
    
    N_NAME("N-NAME"),
    
    QUALIFIER("QUALIFIER"),
    
    NONE("NONE");

    private String value;

    ModifierEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ModifierEnum fromValue(String value) {
      for (ModifierEnum b : ModifierEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MODIFIER = "modifier";
  private ModifierEnum modifier = ModifierEnum.NONE;

  /**
   * Grammatical number
   */
  public enum NumberEnum {
    SINGULAR("SINGULAR"),
    
    PLURAL("PLURAL"),
    
    DUAL("DUAL"),
    
    NONE("NONE");

    private String value;

    NumberEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static NumberEnum fromValue(String value) {
      for (NumberEnum b : NumberEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_NUMBER = "number";
  private NumberEnum number = NumberEnum.NONE;

  /**
   * Grammatical person (for VERBS)
   */
  public enum PersonEnum {
    FIRST("FIRST"),
    
    SECOND("SECOND"),
    
    THIRD("THIRD"),
    
    NONE("NONE");

    private String value;

    PersonEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PersonEnum fromValue(String value) {
      for (PersonEnum b : PersonEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PERSON = "person";
  private PersonEnum person = PersonEnum.NONE;


  public GrammarAnnotation pos(PosEnum pos) {
    
    this.pos = pos;
    return this;
  }

   /**
   * Part of speech
   * @return pos
  **/
  @ApiModelProperty(required = true, value = "Part of speech")
  @JsonProperty(JSON_PROPERTY_POS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PosEnum getPos() {
    return pos;
  }


  public void setPos(PosEnum pos) {
    this.pos = pos;
  }


  public GrammarAnnotation modifier(ModifierEnum modifier) {
    
    this.modifier = modifier;
    return this;
  }

   /**
   * Part of speech modifier
   * @return modifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Part of speech modifier")
  @JsonProperty(JSON_PROPERTY_MODIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ModifierEnum getModifier() {
    return modifier;
  }


  public void setModifier(ModifierEnum modifier) {
    this.modifier = modifier;
  }


  public GrammarAnnotation number(NumberEnum number) {
    
    this.number = number;
    return this;
  }

   /**
   * Grammatical number
   * @return number
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Grammatical number")
  @JsonProperty(JSON_PROPERTY_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public NumberEnum getNumber() {
    return number;
  }


  public void setNumber(NumberEnum number) {
    this.number = number;
  }


  public GrammarAnnotation person(PersonEnum person) {
    
    this.person = person;
    return this;
  }

   /**
   * Grammatical person (for VERBS)
   * @return person
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Grammatical person (for VERBS)")
  @JsonProperty(JSON_PROPERTY_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PersonEnum getPerson() {
    return person;
  }


  public void setPerson(PersonEnum person) {
    this.person = person;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GrammarAnnotation grammarAnnotation = (GrammarAnnotation) o;
    return Objects.equals(this.pos, grammarAnnotation.pos) &&
        Objects.equals(this.modifier, grammarAnnotation.modifier) &&
        Objects.equals(this.number, grammarAnnotation.number) &&
        Objects.equals(this.person, grammarAnnotation.person) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pos, modifier, number, person, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GrammarAnnotation {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    pos: ").append(toIndentedString(pos)).append("\n");
    sb.append("    modifier: ").append(toIndentedString(modifier)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

