/*
 * Isagog Knowledge Graph Service
 * Isagog Knowledge Graph Service API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ks-api@isagog.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.isagog.kg.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.isagog.kg.model.EntityStatement;
import com.isagog.kg.model.KnowledgeAnnotation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Set of statements about conceptualized entities
 */
@ApiModel(description = "Set of statements about conceptualized entities")
@JsonPropertyOrder({
  KnowledgeGraph.JSON_PROPERTY_ID,
  KnowledgeGraph.JSON_PROPERTY_SOURCES,
  KnowledgeGraph.JSON_PROPERTY_DESCRIPTION,
  KnowledgeGraph.JSON_PROPERTY_SIZE,
  KnowledgeGraph.JSON_PROPERTY_ONTOLOGIES,
  KnowledgeGraph.JSON_PROPERTY_CONTEXT,
  KnowledgeGraph.JSON_PROPERTY_CONTENT,
  KnowledgeGraph.JSON_PROPERTY_ANNOTATIONS
})
@JsonTypeName("KnowledgeGraph")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-07T16:45:57.251979+02:00[Europe/Berlin]")
public class KnowledgeGraph {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_SOURCES = "sources";
  private List<URI> sources = null;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_SIZE = "size";
  private Integer size;

  public static final String JSON_PROPERTY_ONTOLOGIES = "ontologies";
  private List<URI> ontologies = null;

  public static final String JSON_PROPERTY_CONTEXT = "context";
  private List<String> context = null;

  public static final String JSON_PROPERTY_CONTENT = "content";
  private List<EntityStatement> content = null;

  public static final String JSON_PROPERTY_ANNOTATIONS = "annotations";
  private List<KnowledgeAnnotation> annotations = null;


  public KnowledgeGraph id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Knowledge Graph id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Knowledge Graph id")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public KnowledgeGraph sources(List<URI> sources) {
    
    this.sources = sources;
    return this;
  }

  public KnowledgeGraph addSourcesItem(URI sourcesItem) {
    if (this.sources == null) {
      this.sources = new ArrayList<URI>();
    }
    this.sources.add(sourcesItem);
    return this;
  }

   /**
   * KG sources
   * @return sources
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "KG sources")
  @JsonProperty(JSON_PROPERTY_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<URI> getSources() {
    return sources;
  }


  public void setSources(List<URI> sources) {
    this.sources = sources;
  }


  public KnowledgeGraph description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * KG description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "KG description")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public KnowledgeGraph size(Integer size) {
    
    this.size = size;
    return this;
  }

   /**
   * Statement number
   * @return size
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Statement number")
  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSize() {
    return size;
  }


  public void setSize(Integer size) {
    this.size = size;
  }


  public KnowledgeGraph ontologies(List<URI> ontologies) {
    
    this.ontologies = ontologies;
    return this;
  }

  public KnowledgeGraph addOntologiesItem(URI ontologiesItem) {
    if (this.ontologies == null) {
      this.ontologies = new ArrayList<URI>();
    }
    this.ontologies.add(ontologiesItem);
    return this;
  }

   /**
   * Ontologies where concepts and relations are defined (URIs)
   * @return ontologies
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ontologies where concepts and relations are defined (URIs)")
  @JsonProperty(JSON_PROPERTY_ONTOLOGIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<URI> getOntologies() {
    return ontologies;
  }


  public void setOntologies(List<URI> ontologies) {
    this.ontologies = ontologies;
  }


  public KnowledgeGraph context(List<String> context) {
    
    this.context = context;
    return this;
  }

  public KnowledgeGraph addContextItem(String contextItem) {
    if (this.context == null) {
      this.context = new ArrayList<String>();
    }
    this.context.add(contextItem);
    return this;
  }

   /**
   * Other graphs providing contextual knowledge
   * @return context
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Other graphs providing contextual knowledge")
  @JsonProperty(JSON_PROPERTY_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getContext() {
    return context;
  }


  public void setContext(List<String> context) {
    this.context = context;
  }


  public KnowledgeGraph content(List<EntityStatement> content) {
    
    this.content = content;
    return this;
  }

  public KnowledgeGraph addContentItem(EntityStatement contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<EntityStatement>();
    }
    this.content.add(contentItem);
    return this;
  }

   /**
   * KG content (statements)
   * @return content
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "KG content (statements)")
  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<EntityStatement> getContent() {
    return content;
  }


  public void setContent(List<EntityStatement> content) {
    this.content = content;
  }


  public KnowledgeGraph annotations(List<KnowledgeAnnotation> annotations) {
    
    this.annotations = annotations;
    return this;
  }

  public KnowledgeGraph addAnnotationsItem(KnowledgeAnnotation annotationsItem) {
    if (this.annotations == null) {
      this.annotations = new ArrayList<KnowledgeAnnotation>();
    }
    this.annotations.add(annotationsItem);
    return this;
  }

   /**
   * KG annotation (application specific)
   * @return annotations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "KG annotation (application specific)")
  @JsonProperty(JSON_PROPERTY_ANNOTATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<KnowledgeAnnotation> getAnnotations() {
    return annotations;
  }


  public void setAnnotations(List<KnowledgeAnnotation> annotations) {
    this.annotations = annotations;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KnowledgeGraph knowledgeGraph = (KnowledgeGraph) o;
    return Objects.equals(this.id, knowledgeGraph.id) &&
        Objects.equals(this.sources, knowledgeGraph.sources) &&
        Objects.equals(this.description, knowledgeGraph.description) &&
        Objects.equals(this.size, knowledgeGraph.size) &&
        Objects.equals(this.ontologies, knowledgeGraph.ontologies) &&
        Objects.equals(this.context, knowledgeGraph.context) &&
        Objects.equals(this.content, knowledgeGraph.content) &&
        Objects.equals(this.annotations, knowledgeGraph.annotations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sources, description, size, ontologies, context, content, annotations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KnowledgeGraph {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sources: ").append(toIndentedString(sources)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    ontologies: ").append(toIndentedString(ontologies)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    annotations: ").append(toIndentedString(annotations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

