/*
 * Isagog Knowledge Graph Service
 * Isagog Knowledge Graph Service API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ks-api@isagog.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.isagog.kg.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.isagog.kg.model.QueryResponseHeader;
import com.isagog.kg.model.QueryResponseItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Query result set
 */
@ApiModel(description = "Query result set")
@JsonPropertyOrder({
  QueryResponse.JSON_PROPERTY_QUERY,
  QueryResponse.JSON_PROPERTY_HEADER,
  QueryResponse.JSON_PROPERTY_ROWS
})
@JsonTypeName("QueryResponse")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-07T16:45:57.251979+02:00[Europe/Berlin]")
public class QueryResponse {
  public static final String JSON_PROPERTY_QUERY = "query";
  private String query;

  public static final String JSON_PROPERTY_HEADER = "header";
  private List<QueryResponseHeader> header = new ArrayList<QueryResponseHeader>();

  public static final String JSON_PROPERTY_ROWS = "rows";
  private List<QueryResponseItem> rows = new ArrayList<QueryResponseItem>();


  public QueryResponse query(String query) {
    
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_QUERY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getQuery() {
    return query;
  }


  public void setQuery(String query) {
    this.query = query;
  }


  public QueryResponse header(List<QueryResponseHeader> header) {
    
    this.header = header;
    return this;
  }

  public QueryResponse addHeaderItem(QueryResponseHeader headerItem) {
    this.header.add(headerItem);
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_HEADER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<QueryResponseHeader> getHeader() {
    return header;
  }


  public void setHeader(List<QueryResponseHeader> header) {
    this.header = header;
  }


  public QueryResponse rows(List<QueryResponseItem> rows) {
    
    this.rows = rows;
    return this;
  }

  public QueryResponse addRowsItem(QueryResponseItem rowsItem) {
    this.rows.add(rowsItem);
    return this;
  }

   /**
   * Get rows
   * @return rows
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ROWS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<QueryResponseItem> getRows() {
    return rows;
  }


  public void setRows(List<QueryResponseItem> rows) {
    this.rows = rows;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryResponse queryResponse = (QueryResponse) o;
    return Objects.equals(this.query, queryResponse.query) &&
        Objects.equals(this.header, queryResponse.header) &&
        Objects.equals(this.rows, queryResponse.rows);
  }

  @Override
  public int hashCode() {
    return Objects.hash(query, header, rows);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryResponse {\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    rows: ").append(toIndentedString(rows)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

