/*
 * Isagog Knowledge Graph Service
 * Isagog Knowledge Graph Service API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ks-api@isagog.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.isagog.kg.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Query result set header
 */
@ApiModel(description = "Query result set header")
@JsonPropertyOrder({
  QueryResponseHeader.JSON_PROPERTY_NAME,
  QueryResponseHeader.JSON_PROPERTY_DTYPE
})
@JsonTypeName("QueryResponseHeader")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-08T12:36:17.061150100+02:00[Europe/Berlin]")
public class QueryResponseHeader {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  /**
   * Gets or Sets dtype
   */
  public enum DtypeEnum {
    URI("Uri"),
    
    BOOLEAN("Boolean"),
    
    INTEGER("Integer"),
    
    DOUBLE("Double"),
    
    STRING("String");

    private String value;

    DtypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DtypeEnum fromValue(String value) {
      for (DtypeEnum b : DtypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DTYPE = "dtype";
  private DtypeEnum dtype;


  public QueryResponseHeader name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public QueryResponseHeader dtype(DtypeEnum dtype) {
    
    this.dtype = dtype;
    return this;
  }

   /**
   * Get dtype
   * @return dtype
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DTYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public DtypeEnum getDtype() {
    return dtype;
  }


  public void setDtype(DtypeEnum dtype) {
    this.dtype = dtype;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryResponseHeader queryResponseHeader = (QueryResponseHeader) o;
    return Objects.equals(this.name, queryResponseHeader.name) &&
        Objects.equals(this.dtype, queryResponseHeader.dtype);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, dtype);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryResponseHeader {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    dtype: ").append(toIndentedString(dtype)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

