/*
 * Isagog Knowledge Graph Service
 * Isagog Knowledge Graph Service API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ks-api@isagog.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.isagog.kg.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.isagog.kg.model.Support;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Slot value instance
 */
@ApiModel(description = "Slot value instance")
@JsonPropertyOrder({
  SlotValue.JSON_PROPERTY_SLOT_TYPE_ID,
  SlotValue.JSON_PROPERTY_SOURCE_TYPE,
  SlotValue.JSON_PROPERTY_VALUE,
  SlotValue.JSON_PROPERTY_SUPPORT
})
@JsonTypeName("SlotValue")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-01T15:11:01.505608900+02:00[Europe/Berlin]")
public class SlotValue {
  public static final String JSON_PROPERTY_SLOT_TYPE_ID = "slotTypeId";
  private String slotTypeId;

  /**
   * The value provenance
   */
  public enum SourceTypeEnum {
    USER_INPUT("USER_INPUT"),
    
    KNOWLEGDE_BASE("KNOWLEGDE_BASE"),
    
    UNDEFINED("UNDEFINED");

    private String value;

    SourceTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SourceTypeEnum fromValue(String value) {
      for (SourceTypeEnum b : SourceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SOURCE_TYPE = "sourceType";
  private SourceTypeEnum sourceType = SourceTypeEnum.UNDEFINED;

  public static final String JSON_PROPERTY_VALUE = "value";
  private byte[] value;

  public static final String JSON_PROPERTY_SUPPORT = "support";
  private Support support;


  public SlotValue slotTypeId(String slotTypeId) {
    
    this.slotTypeId = slotTypeId;
    return this;
  }

   /**
   * Slot type&#39;s identifier
   * @return slotTypeId
  **/
  @ApiModelProperty(required = true, value = "Slot type's identifier")
  @JsonProperty(JSON_PROPERTY_SLOT_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSlotTypeId() {
    return slotTypeId;
  }


  public void setSlotTypeId(String slotTypeId) {
    this.slotTypeId = slotTypeId;
  }


  public SlotValue sourceType(SourceTypeEnum sourceType) {
    
    this.sourceType = sourceType;
    return this;
  }

   /**
   * The value provenance
   * @return sourceType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The value provenance")
  @JsonProperty(JSON_PROPERTY_SOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SourceTypeEnum getSourceType() {
    return sourceType;
  }


  public void setSourceType(SourceTypeEnum sourceType) {
    this.sourceType = sourceType;
  }


  public SlotValue value(byte[] value) {
    
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public byte[] getValue() {
    return value;
  }


  public void setValue(byte[] value) {
    this.value = value;
  }


  public SlotValue support(Support support) {
    
    this.support = support;
    return this;
  }

   /**
   * Get support
   * @return support
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUPPORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Support getSupport() {
    return support;
  }


  public void setSupport(Support support) {
    this.support = support;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SlotValue slotValue = (SlotValue) o;
    return Objects.equals(this.slotTypeId, slotValue.slotTypeId) &&
        Objects.equals(this.sourceType, slotValue.sourceType) &&
        Arrays.equals(this.value, slotValue.value) &&
        Objects.equals(this.support, slotValue.support);
  }

  @Override
  public int hashCode() {
    return Objects.hash(slotTypeId, sourceType, Arrays.hashCode(value), support);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SlotValue {\n");
    sb.append("    slotTypeId: ").append(toIndentedString(slotTypeId)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    support: ").append(toIndentedString(support)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

