/*
 * Isagog Knowledge Graph Service
 * Isagog Knowledge Graph Service API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ks-api@isagog.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.isagog.kg.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Knowledge support score
 */
@ApiModel(description = "Knowledge support score")
@JsonPropertyOrder({
  Support.JSON_PROPERTY_EVIDENCE,
  Support.JSON_PROPERTY_CONFIDENCE
})
@JsonTypeName("Support")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-08T12:36:17.061150100+02:00[Europe/Berlin]")
public class Support {
  public static final String JSON_PROPERTY_EVIDENCE = "evidence";
  private Double evidence = 0.5d;

  public static final String JSON_PROPERTY_CONFIDENCE = "confidence";
  private Double confidence = 0.5d;


  public Support evidence(Double evidence) {
    
    this.evidence = evidence;
    return this;
  }

   /**
   * Evidence score [1&#x3D;Positive evidence, 0&#x3D;Negative evidence]
   * @return evidence
  **/
  @ApiModelProperty(required = true, value = "Evidence score [1=Positive evidence, 0=Negative evidence]")
  @JsonProperty(JSON_PROPERTY_EVIDENCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getEvidence() {
    return evidence;
  }


  public void setEvidence(Double evidence) {
    this.evidence = evidence;
  }


  public Support confidence(Double confidence) {
    
    this.confidence = confidence;
    return this;
  }

   /**
   * Confidence score [1&#x3D;Full confidence, 0&#x3D;No confidence]
   * @return confidence
  **/
  @ApiModelProperty(required = true, value = "Confidence score [1=Full confidence, 0=No confidence]")
  @JsonProperty(JSON_PROPERTY_CONFIDENCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getConfidence() {
    return confidence;
  }


  public void setConfidence(Double confidence) {
    this.confidence = confidence;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Support support = (Support) o;
    return Objects.equals(this.evidence, support.evidence) &&
        Objects.equals(this.confidence, support.confidence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(evidence, confidence);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Support {\n");
    sb.append("    evidence: ").append(toIndentedString(evidence)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

