/*
 * Isagog Knowledge Graph Service
 * Isagog Knowledge Graph Service API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ks-api@isagog.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.isagog.kg.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * TextualContent
 */
@JsonPropertyOrder({
  TextualContent.JSON_PROPERTY_LANG,
  TextualContent.JSON_PROPERTY_TEXT,
  TextualContent.JSON_PROPERTY_CONTEXT
})
@JsonTypeName("TextualContent")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-08T12:36:17.061150100+02:00[Europe/Berlin]")
public class TextualContent {
  /**
   * Language
   */
  public enum LangEnum {
    EN("en"),
    
    ES("es"),
    
    FR("fr"),
    
    IT("it"),
    
    DE("de");

    private String value;

    LangEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LangEnum fromValue(String value) {
      for (LangEnum b : LangEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LANG = "lang";
  private LangEnum lang;

  public static final String JSON_PROPERTY_TEXT = "text";
  private byte[] text;

  public static final String JSON_PROPERTY_CONTEXT = "context";
  private byte[] context;


  public TextualContent lang(LangEnum lang) {
    
    this.lang = lang;
    return this;
  }

   /**
   * Language
   * @return lang
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Language")
  @JsonProperty(JSON_PROPERTY_LANG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LangEnum getLang() {
    return lang;
  }


  public void setLang(LangEnum lang) {
    this.lang = lang;
  }


  public TextualContent text(byte[] text) {
    
    this.text = text;
    return this;
  }

   /**
   * Textual content
   * @return text
  **/
  @ApiModelProperty(required = true, value = "Textual content")
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public byte[] getText() {
    return text;
  }


  public void setText(byte[] text) {
    this.text = text;
  }


  public TextualContent context(byte[] context) {
    
    this.context = context;
    return this;
  }

   /**
   * Textual context
   * @return context
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Textual context")
  @JsonProperty(JSON_PROPERTY_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getContext() {
    return context;
  }


  public void setContext(byte[] context) {
    this.context = context;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TextualContent textualContent = (TextualContent) o;
    return Objects.equals(this.lang, textualContent.lang) &&
        Arrays.equals(this.text, textualContent.text) &&
        Arrays.equals(this.context, textualContent.context);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lang, Arrays.hashCode(text), Arrays.hashCode(context));
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TextualContent {\n");
    sb.append("    lang: ").append(toIndentedString(lang)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

